apiVersion: v1
kind: Service
metadata:
  name: ${JOB_NAME}-jobmanager
  labels:
    app: flink
    component: ${JOB_NAME}-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
  selector:
    app: flink
    component: ${JOB_NAME}-jobmanager
